icons_format = "{icon}"

[theme]
theme = "modern"
[theme.overrides]
idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^|"

[[block]]
block = "custom"

command = "~/myScripts/powerAndlock.sh idleToggleStatus"
shell = "bash"
interval=1

json = true

[[block.click]]
button = "left"
cmd = "~/myScripts/powerAndlock.sh idleToggle"


[[block]]
block = "custom"
json = true
command = "~/myScripts/swaybar/i3StatusBarRsMedia.sh"
interval = 5
shell = "bash"


[[block]]
block = "custom"
command = "echo 📦 $(sudo paru -Syy > /dev/null &&  paru -Qu | wc -l)"
interval = 3600
shell = "bash"
#[[block.click]]
#button = "left"
#cmd = "konsole -e '$SHELL -c \"paru -Syyu\"'"

[[block]]
block = "net"
format = " $icon { $ip ▼$speed_down ▲$speed_up }"

[[block]]
block = "load"
format = "🏋 $1m.eng(w:4)"
interval = 3
info = 1
warning = 3
critical = 5

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "/: $available.eng(w:2)"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "/home: $available.eng(w:2)"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
warning_mem=70
critical_mem=90

[[block]]
block = "sound"
format = " $icon  $output_name{ $volume|}"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.mappings]
"bluez_output.*"="B"
"alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Headphones__sink"="H"
"alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.*"="S"
[[block]]              
block = "bluetooth"              
mac = "00:A4:1C:4D:D4:C1"             
disconnected_format = ""              
format = " $icon $percentage"              
[block.battery_state]     
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d/%m %r')"

[[block]]
block = "battery"


